---

- hosts: webservers
  tasks:
   - name: Install forever
     npm: name=forever global=yes state=present

   - name: npm installation
     command: npm install #- name: perform  cloning git
8
     #command: git clone https://github.com/Thirupathichalla-arch/SonarQubeNodeJS.git ~/SonarQubeNodeJS
     args:
       chdir: ~/SonarQubeNodeJS

   - name: execute npm
     command: forever start SonarQubeNodeJS/app/views/index.html
